### ISSUE TITLE
not re-rendering on redux

### ISSUE THREAD

**Issue by dpereira411** [ctrlplusb/react-sizeme#1]
its not working with redux, the reducers are not re-rendering the component

I'm using the default configuration and any actions that i trigger on the container are only presented to the screen after a window resize.

**Comment by ctrlplusb** [comment]
Any chance you could share your configuration or an example of this. I'm happy to debug and fix it for you.

**Comment by ctrlplusb** [comment]
Had a think. Yep this is my issue. As a temp fix change your code so that the SizeMe HOC call is the last in your compose stack.

E.g.

```
import { compose, connect } from 'react-redux';
import SizeMe from 'react-sizeme';

function FooComponent(props) {
 ...
}

export compose(
  SizeMe(),
  connect(...)
)(FooComponent);
```

I'll release a fix tomorrow. Out celebrating Liverpool's epic win! :-D

**Comment by dpereira411** [comment]
thanks :) congratulations, great club and and great game

**Comment by ctrlplusb** [comment]
Thanks!  

All sorted on your bug.  Thanks for the report! 💖

**Comment by dpereira411** [comment]
thanks :)
