### ISSUE TITLE
Need to call a function on a wrapped component

### ISSUE THREAD

**Issue by JaneCoder** [ctrlplusb/react-sizeme#100]
Hello,

Thanks for this product! 

I have a component that I need to call a data refresh method on when it is unhidden from a view.  Wrapping it in sizeme was great for helping it to size correctly, but now I can't access it to call the refresh because the object is now a resizeme thing, instead of the old component with the refresh function.

How can I send a message to the object inside sizeme?

**Comment by ctrlplusb** [comment]
Haha, the universe is cruel!  I just closed a related issue (#12) today as it didn't get a lot of attention.

I'll have to reconsider this.  Most likely I'll exposed the wrapped instance via a property.  Stay tuned..

**Comment by adi3112** [comment]
I'm having the same problem, need to call a function inside of this Size me component.

**Comment by alaindresse** [comment]
Here is a way to do it without changing sizeme: create your own 'ref' prop:

```
class SizedImageImpl extends React.Component {
    props: {
        src: string,
        size:{height:number},
        innerRef?: () => (void) => number;
    }

    componentDidMount(){
        this.props.innerRef && this.props.innerRef(this);
    }

    componentWillUnmount(){
        this.props.innerRef && this.props.innerRef(undefined);
    }

    getHeight(){
        return this.props.size.height;
    }

    render(){
        return <Image src={this.props.src} />
    }
}

import sizeMe from 'react-sizeme';
var SizedImage =  sizeMe({ monitorWidth: false, monitorHeight: true })(SizedImageImpl);
```

Then if you use
```
<SizedImage src={imageUrl} innerRef={node => this.imageNode = node} />
```
you can call `this.imageNode.getHeight()`

**Comment by JaneCoder** [comment]
@alaindresse thanks! and how would you get a handle on the wrapped object in a jest test?

**Comment by JaneCoder** [comment]
PS, my component does a 

module.exports = sizeme()(MyComponent);

So it comes wrapped everywhere right now.

**Comment by ctrlplusb** [comment]
Hey @JaneCoder 

IMO you have two options.

1. Use the `WrappedComponent` that we provide on all `sizeMe` wrapped components.

// MySizedComponent.test.js
```javascript
import MySizedComponent from './MySizedComponent'

const MyComponent = MySizedComponent.WrappedComponent

describe('foo', () => {
  it('bar', () => {
    expect(shallow(<MyComponent />)).toMatchSnapshot()
  })
})
```

2. Export your raw component as well as the `sizeMe` wrapped component.

// MySizedComponent.js
```
import React from 'react'
import sizeMe from 'react-sizeme'

export function MyComponent() {
  return <span>👋</span>
}

export default sizeMe()(MyComponent)
```

// MySizedComponent.test.js
```javascript
import { MyComponent } from './MySizedComponent'

describe('foo', () => {
  it('bar', () => {
    expect(shallow(<MyComponent />)).toMatchSnapshot()
  })
})
```

Personally I prefer option number 2 as it's less likely to break should you wrap your component with another higher order component. 👍

**Comment by JaneCoder** [comment]
Sweet. Thanks. I did not know I could grab the wrapped component like that. 
You rock!

And Redux is going to make me like idea #2 a lot as well.

**Comment by ahmadsholehin** [comment]
Sorry for the revive. From my understanding, `WrappedComponent` returns the class of the wrapped component, not the instance.

What do we do if we want to call a function on a mounted instance via ref?

```
refSizedComponent ( ref ) {
  this.sizedComponent = ref;
}

...

<SizedComponent
  ref={ this.refSizedComponent }
/>

// then later on
this.sizedComponent.internalFunction(); // this does not work since the internal component has been wrapped
```

Am I doing this wrong?
