### ISSUE TITLE
Element position tracking

### ISSUE THREAD

**Issue by fckt** [ctrlplusb/react-sizeme#103]
First of all I want to say thanks for the great work, I love the idea! 👍 

I thought to make similar thing, but found `react-sizeme` could be a pretty good fit in my case..

The question is: why not to add the position tracking also?.. I'm working on drag'n'drop example in [react-layer-stack](https://github.com/fckt/react-layer-stack) and I what I need is to track the actual positions and sizes of "dropzones". What do you think?

**Comment by ctrlplusb** [comment]
Hey @fckt!

Thanks!  I finally got round to doing this.  Great idea thanks, and it opens up a world of opportunities.  I have yet to release it, but the release soon be soon.
