### ISSUE TITLE
invalid element-resize-detector dist file causes minification errors

### ISSUE THREAD

**Issue by rosskevin** [ctrlplusb/react-sizeme#104]
`react-sizeme` depends on `element-resize-detector` and it currently fails minification with `babili` due to an error I reported over there: https://github.com/wnr/element-resize-detector/issues/71

This was a bit painful to track down because the code is obfuscated.  

This is a production show-stopper for me; hoping for a quick resolution over there because I'm unfamiliar with browserify.  If someone here is familiar with browserify, I would think it's a quick fix.  Once fixed, we'll need a new release of `react-sizeme`.

**Comment by ctrlplusb** [comment]
Hey @rosskevin please ping me when things with `element-resize-detector` get resolved. I want to give this library a maintenance round but will wait till then. x
