### ISSUE TITLE
Render props pattern usage

### ISSUE THREAD

**Issue by chrisdrackett** [ctrlplusb/react-sizeme#105]
Have you ever considered having sizeMe work where you use a `<SizeMe>` component and it passes the size down as a prop? I think this method feels a bit more readable. ReactMotion does something like this.

```jsx
<SizeMe monitorHeight>
    {size => <div>{size.width}, {size.height}</div>}
</SizeMe>
```

**Comment by ctrlplusb** [comment]
It's an interesting concept.  Although we would have to make the `SizeMe` component render out a `div` or something similar, which would then be measured and then it's size would be passed down into the render callback function.  

Additional props could be applied to the div (outside of the expected SizeMe config props) - such as  className/style etc, and we could even support a `tag` prop so you can change the container type (e.g. div/span etc).

This could be just a special component that encapsulates the existing API.  Are you happy to experiment in creating this wrapper component? And then we could look at incorporating it if we found it useful.

**Comment by chrisdrackett** [comment]
could `SizeMe` just clone its child and make sure that only a single child is ever sent?

**Comment by ctrlplusb** [comment]
Yeah, that sounds like an option. 😀

I would love for us to explore this more.  Are you up for starting up a PR?

**Comment by chrisdrackett** [comment]
I am!

**Comment by ctrlplusb** [comment]
Awesome! Shout if you need anything. 😊

**Comment by chrisdrackett** [comment]
actually I might have spoken too soon, I'm going to take a look at https://github.com/souporserious/react-measure first, as it seems to support this format already and we have other components that also use it already.

Not that I'm against helping out, it just might not be right away 😊

**Comment by ctrlplusb** [comment]
Started to flesh out an API: https://codesandbox.io/s/oxkw6xv4z6

**Comment by ctrlplusb** [comment]
Published a new version including a render props pattern based component 🎉
