### ISSUE TITLE
Size in readme

### ISSUE THREAD

**Issue by ismay** [ctrlplusb/react-sizeme#108]
I was wondering whether the size of this lib, as reported in the readme, is still correct. For me, when only minified, this lib adds 148kB (when bundled separately, with webpack).

When testing the gzip compression with https://closure-compiler.appspot.com/home, I get the following gzip size:

```
Original Size:
44.6KB gzipped (144.64KB uncompressed)
Compiled Size:
39.17KB gzipped (108.37KB uncompressed)

Saved 12.17% off the gzipped size (25.08% without gzip)
```

So it compresses down to roughly 45kB gzipped. Now I'm assuming that the difference isn't just webpack bundling overhead. Do you know why my results are so different from the 9kB from the readme, am I overlooking something?

**Comment by ctrlplusb** [comment]
Are you using the latest version?  It may be pulling across the whole of `lodash`?  I thought we did a fix for this recently.  Thanks for the report I will double check this.

**Comment by ctrlplusb** [comment]
Yeah, something is defo up here!  

Will add a high priority fix for this.

**Comment by ismay** [comment]
> Are you using the latest version?

Yep, using 2.3.1

**Comment by ctrlplusb** [comment]
Hey @ismay 

I just added this to a fresh project and did an analyze.  It added the expected overhead.

<img width="235" alt="screenshot 2017-04-05 14 49 11" src="https://cloud.githubusercontent.com/assets/12164768/24708591/3378faba-1a0f-11e7-8236-21095afd2b7d.png">

Are you using lodash at all in your project?

**Comment by ismay** [comment]
> Are you using lodash at all in your project?

Not in my own code (but probably in other libs). The problem probably lies elsewhere then, I'm running into a similar issue with styled-components, so I'm assuming it's not related to this lib. Thanks for the quick replies!

**Comment by ctrlplusb** [comment]
No problem.  Good luck!
