### ISSUE TITLE
Proposal: add refreshDelayStrategy config option

### ISSUE THREAD

**Issue by alexesDev** [ctrlplusb/react-sizeme#109]
Add `refreshDelayStrategy` config option, remove lodash dependency and recude a lib size.

```js
import sizeMe from 'react-sizeme';
import debounce from 'debounce';

export default sizeMe({
  refreshDelayStrategy: (work) => debounce(work, 16),
});
```

We have a lot of dependencies in our projects. If each lib reduce size by few kb... its ~30*4=120Kb...

**Comment by ctrlplusb** [comment]
Very interesting proposal!

**Comment by ctrlplusb** [comment]
Not needed anymore. I've switched to a much smaller library.

Old:
https://bundlephobia.com/result?p=react-sizeme@2.6.6

New:
https://bundlephobia.com/result?p=react-sizeme@2.6.7
