### ISSUE TITLE
Flex support

### ISSUE THREAD

**Issue by binchik** [ctrlplusb/react-sizeme#110]
Hello, thanks for your awesome work!

I cannot make `sizeme` work with flex positioning. I'm tracking width and the size is updated only if component gets wider. If it becomes narrower, size does not change.

**Comment by ctrlplusb** [comment]
Hey @binchik, thanks!

Have you used the `monitorHeight: true` config? By default it doesn't monitor height or position - to avoid thrashing.

**Comment by binchik** [comment]
@ctrlplusb, I tried `monitorHeight: true`, got the same result :(. BTW, I'm using SSR (I set `noPlaceholder: true`). I switched flex to relative positioning and now everything works fine.

**Comment by ctrlplusb** [comment]
Great, thanks for the feedback on this. Good to know.
