### ISSUE TITLE
How to set layout component height = window height?

### ISSUE THREAD

**Issue by thearabbit** [ctrlplusb/react-sizeme#111]
I would like to set my layout component height `Content` = windows height
```js
                        <Content style={{minHeight: .....}}>
                            
                        </Content>

```
Please help me.

**Comment by ctrlplusb** [comment]
You could use a css property for this. :)

```
<Content style={{ minHeight: '100vh' }} />
```

Read more [here](https://css-tricks.com/forums/topic/viewport-height-for-full-screen-div/)

**Comment by thearabbit** [comment]
Thanks for your reply.
I will try soon.
