### ISSUE TITLE
Fix PropTypes  deprecated Warning

### ISSUE THREAD

**Issue by RathanakSreang** [ctrlplusb/react-sizeme#112]
When I try to use `react-sizeme`, it shows this warning in my console.
`Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.`
So how can I fix it?
Here the code I implement.
```
class CassettePlayer extends Component {
}

import sizeMe from 'react-sizeme';
export default sizeMe()(CassettePlayer);
```

**Comment by ctrlplusb** [comment]
This is due to you using [React v15.5](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html)

Eventually this library and the reset of the eco system will catch up. Please see the linked blog post for more info.
