### ISSUE TITLE
The observer stops working when component content is replaced

### ISSUE THREAD

**Issue by wojciech-skowronek** [ctrlplusb/react-sizeme#118]
The observer stops working when component content is replaced. This may be an issue especially with simple (e.g. text only) components.

My component looks like:
```
  render(): JSX.Element {
    return (
      <div className="ellipsis">{this.state.truncatedText}</div>
    );
  }
```
When state changes it will replace text and also remove `.erd_scroll_detection_container` element. There s error message and it makes it quite hard to debug. Simple solution is to wrap this.state.truncatedText in one more element e.g:

```
  render(): JSX.Element {
   return (
      <div className="ellipsis" ref="container">
        <span>{this.state.truncatedText}</span>
      </div>
    );
  }
```

I believe it's worth to add info about DOM modyfication in the readme.

**Comment by ctrlplusb** [comment]
Yeah please see #98

Happy to accept a PR to add this to the readme. 👍

**Comment by ctrlplusb** [comment]
This is no longer an issue.

https://codesandbox.io/s/311r2x279m
