### ISSUE TITLE
nextProps and this.props always have the same size properties

### ISSUE THREAD

**Issue by sanpoChew** [ctrlplusb/react-sizeme#119]
I was originally trying to use react-component-queries but I noticed that my queries were only ever run once on first render, after then trying to implement my own version of it using shouldComponentUpdate and react-sizeme I ran into this issue which seems to be the root of my original problem. I'm not that good with Chrome Devtools but it _seems_ that when strategisedSetState is called that is also somehow bypassing shouldComponentUpdate and mutating the props object. I have noPlaceholder set to true as we are using SSR, but apart from that am not doing anything out of the ordinary.

Any help with this would be appreciated.

**Comment by ctrlplusb** [comment]
Hmmm, does this issue only appear on the server render? If not any chance of creating a minimal reproduction using something like codesandbox.io?  Thanks!

**Comment by sanpoChew** [comment]
@ctrlplusb it's not just the server render, I'll try and get something up today. Just a quick thought though, do you think the fact we're using preact could be an issue?

**Comment by sanpoChew** [comment]
@ctrlplusb So I seem to have found the issue, changing the render function of SizeAwareComponent to make a copy of this.state and pass that as props to SizeMeRenderWrapper instead of just passing down this.state directly seems to fix it. I'm guessing that it was Preact handling things slightly different that may have caused this issue? I'm happy to submit a merge request if you'd like. Thanks!

**Comment by ctrlplusb** [comment]
Hi @sanpoChew 

I am always open to PR's that address issues. Thank you very much for taking the time to identify the issue and come up with a possible solution! ❤️
