### ISSUE TITLE
Expose a reference to the wrapped component

### ISSUE THREAD

**Issue by mjtamlyn** [ctrlplusb/react-sizeme#12]
It would be useful if we could access functions of the original component. It's an usual requirement, but it is a [documented pattern](https://facebook.github.io/react/tips/expose-component-functions.html).

I think the easiest way to achieve this is to make sure that the `SizeMe` container has a `ref` to the component passed into it. That way the parent of the `SizeMe` wrapper can call `this.refs.wrapped.refs.original.doSomething()`.

**Comment by ctrlplusb** [comment]
Yep, sounds reasonable.  Just fleshing out how to add this to the API.  I am thinking of making it an opt-in behaviour.

**Comment by mjtamlyn** [comment]
Thinking about it, as it isn't a dom node component it doesn't necessarily need to be a ref of the wrapping component, could just be an attribute with a functional ref which updates it.

**Comment by ctrlplusb** [comment]
I haven't had any further requests on this so I am going to close this for now.
