### ISSUE TITLE
Basic example not working

### ISSUE THREAD

**Issue by Ribesg** [ctrlplusb/react-sizeme#128]
I was trying to use react-sizeme in my project and it didn't work.

So I tried setting up a basic working sandbox, and it doesn't work either.

What am I missing?

https://codesandbox.io/s/pwlyw09kxj

**Comment by ctrlplusb** [comment]
Ah, this looks like an issue with the way you have set up your styles. You were "fixing" the dimensions of your box.  I adapted it to make it responsive.

https://codesandbox.io/s/48n005q5nx

i.e. I changed

```
  <div
    style={{
      width: `${size.width}px`,
      height: `${size.height}px`,
```

to

```
  <div
    style={{
      width: '100%',
      height: '100%',
```

**Comment by Ribesg** [comment]
I managed to make a working example: https://codesandbox.io/s/zr5r1qq6np

What I didn't understand is that react-sizeme detects resizes of the root of your component by the browser, so fixing the size of the root component does not work!
