### ISSUE TITLE
Typescript definitions

### ISSUE THREAD

**Issue by xaviergonz** [ctrlplusb/react-sizeme#130]
Could there be any typescript definitions?

Right now I made the following in my own code to create them, but it would be cool if they were on the package:

```js
type Omit<T, K> = Pick<T, Exclude<keyof T, K>>;

export interface SizeMeProps {
  size: {
    width: number | null;
    height: number | null;
  };
}

export interface SizeMeOptions {
  monitorWidth?: boolean;
  monitorHeight?: boolean;
  monitorPosition?: boolean;
  refreshRate?: number;
  refreshMode?: 'throttle' | 'debounce';
  noPlaceholder?: boolean;
}

type SizeMeFunction = (options?: SizeMeOptions) => <P extends SizeMeProps>(component: React.ComponentType<P>) => React.ComponentType<Omit<P, 'size'>>;

export const sizeMe: SizeMeFunction = require('react-sizeme');
```

**Comment by ctrlplusb** [comment]
Create a PR, I am happy to accept! 😀

**Comment by xaviergonz** [comment]
Updated to TS2.8 and sizeme 2.4.x (now the function is not exported as "default" anymore)

**Comment by bytenik** [comment]
@xaviergonz Are you going to PR this?

**Comment by hidai** [comment]
any progress?

**Comment by ctrlplusb** [comment]
@hidai open to PRs :)

**Comment by wisaac407** [comment]
When will this make it to an npm release?

**Comment by mwickett** [comment]
Can we get an NPM release that includes the TS definitions that have been merged? Thanks!

**Comment by truesdan** [comment]
@ctrlplusb Is there an upcoming NPM release planned that will include the typescript types? I'd love to use this but don't want to define the types manually in case they change in a future release.

**Comment by koprivajakub** [comment]
@ctrlplusb Any update on the issue or can you make a release just with the typings? This would be very helpful.

**Comment by ctrlplusb** [comment]
Hey all, much apologies for lack of maintenance on this. I am going to do a wide update this weekend. I have developed knowledge of Typescript now via my other project, easy-peasy. This should help me ensure the definitions are solid.

**Comment by ctrlplusb** [comment]
This is published. I've added tests to the types and made one minor adjustment to them. 👍

**Comment by DoubleFinned** [comment]
I'm still getting the 'could not find declaration file' error on NPM version 2.6.2. Have verified that I've installed 2.6.2 by running `yarn list --pattern react-sizeme`

**Comment by ctrlplusb** [comment]
Thanks publishing fix
