### ISSUE TITLE
Change componentWillReceiveProps implementation

### ISSUE THREAD

**Issue by drgx** [ctrlplusb/react-sizeme#148]
React will deprecate `componentWillReceiveProps` soon, consider to update the implementation to use `getDerivedStateFromProps`.
https://github.com/ctrlplusb/react-sizeme/blob/master/src/with-size.js#L193

**Comment by ctrlplusb** [comment]
Hey @drgx - would you be up for creating a PR? :)

**Comment by drgx** [comment]
Sure.. but my friend already send the PR https://github.com/ctrlplusb/react-sizeme/pull/149 ... haha..

**Comment by ctrlplusb** [comment]
Merged 👍
