### ISSUE TITLE
Getting error when using typescript module esnext

### ISSUE THREAD

**Issue by abhikapuria** [ctrlplusb/react-sizeme#155]
Hi,

I was trying to implement code splitting in my application which has been written using typescript. When in ts.config I have module as commonjs everything works fine but as soon as I change it to esNext I am getting below error,

Functions are not valid as a React child. This may happen if you return a Component instead of <Component /> from render. Or maybe you meant to call this function rather than return it.
    in **withSize** 

Any suggestions would help.

**Comment by ctrlplusb** [comment]
Please ensure you are importing the render props component as:

```
import { SizeMe } from 'react-sizeme';
```
