### ISSUE TITLE
FirstTime render will flicker once in react.Component

### ISSUE THREAD

**Issue by catXiaoXiao** [ctrlplusb/react-sizeme#158]
please handle this problem,thanks.
"react": "^16.2.0"

**Comment by larrydahooster** [comment]
You can't avoid the flicker. That is caused by how react-sizeme works. In order to know about the height of the parent element, the parent element needs to be rendered first without the child. Once the parent is rendered first, the child can know about it's parent dimensions.

**Comment by ctrlplusb** [comment]
@catXiaoXiao you can pass the option to disable the placeholder (via `noPlaceholder`). This will ensure your actual component is rendered. However, the size values will be null until your component is measured. So you will have to account for this.
