### ISSUE TITLE
One issue in getting the height

### ISSUE THREAD

**Issue by sueyan2018** [ctrlplusb/react-sizeme#159]
I use sizeme to wrap a chart component，and sizeme is inside a grid， but I cannot get the height of the grid，size.height is the height of winWindows , I'm wondering how it can be corrected.
The structure is like this:
<Grid>
      <SizeMe
          monitorHeight
          refreshRate={32}
          render={({ size }) =>  
          
            <LineChart
                data={data2}
                width={size.width}
                height={size.height}
                />
          }
        />
</Grid> 

Looking forward to your reply, thanks a lot.

**Comment by mj1856** [comment]
Maybe the approach I describe [here](https://github.com/ctrlplusb/react-sizeme/issues/120#issuecomment-446421690) would help you?

**Comment by ctrlplusb** [comment]
@sueyan2018 let me know how it went for you. Closing this for now.
