### ISSUE TITLE
Warning: Functions are not valid as a React child.

### ISSUE THREAD

**Issue by iTonyYo** [ctrlplusb/react-sizeme#165]
It's OK when using the `sizeMe` hoc.

The error below always shows when using `<SizeMe />` (`children` and `render` prop). **Here's an [example](https://codesandbox.io/s/0x6j65928n).**

![image](https://user-images.githubusercontent.com/5499703/53780688-6ebf5300-3f40-11e9-9167-fd7b339df208.png)

**Comment by kaielvin** [comment]
`import {SizeMe} from 'react-sizeme';`
NOT
`import SizeMe from 'react-sizeme';`
