### ISSUE TITLE
sizeMe HOC does not work correctly with React.Fragment

### ISSUE THREAD

**Issue by loganmay** [ctrlplusb/react-sizeme#172]
I had a some code along the lines of 

**MyComponent.jsx**

    import React, { Component } from 'react';
    import sizeMe from 'react-sizeme';
    
    class MyComponent extends Component {
      // Stuff
      render() {
        console.log(this.props.size);
        return (
          <React.Fragment>
            // JSX
          </React.Fragment>
        )
      }
    }

    export default sizeMe()(MyComponent);

**AnotherComponent.jsx**

    import React from 'react';
    
    const AnotherComponent = _ => <MyComponent style={{width: '100%'}} />;
    
    export default AnotherComponent;

The logs showed that the component rendered twice, the first time with the correct width, and height and position set to null. Then, the second time the height was some seemingly random very small value, ~46px for an element that has its style width set to 100% of the page.

Simply swapping `React.Fragment` for a plain old `div` resolved it. 

**package.json (part)**
      "scripts": {
        "build": "./node_modules/.bin/webpack -w",
        "start:dev": "./node_modules/.bin/webpack-dev-server"
      },
      "dependencies": {
        "prop-types": "^15.7.2",
        "react": "^16.8.6",
        "react-dom": "^16.8.6",
        "react-redux": "^7.1.0",
        "react-sizeme": "^2.6.7",
        "react-stonecutter": "^0.3.10",
        "redux": "^4.0.4"
      },
      "devDependencies": {
        "@babel/core": "^7.4.5",
        "@babel/plugin-proposal-class-properties": "^7.5.5",
        "@babel/preset-env": "^7.4.5",
        "@babel/preset-react": "^7.0.0",
        "babel-loader": "^8.0.6",
        "css-loader": "^3.0.0",
        "file-loader": "^4.0.0",
        "html-webpack-plugin": "^3.2.0",
        "mini-css-extract-plugin": "^0.7.0",
        "node-sass": "^4.12.0",
        "sass-loader": "^7.1.0",
        "style-loader": "^0.23.1",
        "url-loader": "^2.0.0",
        "webpack": "^4.35.0",
        "webpack-cli": "^3.3.5",
        "webpack-dev-server": "^3.7.2"
      }

If you'd like more details, I'm happy to speak, just reach out. Thanks for the great component!

**Comment by ctrlplusb** [comment]
Hey @loganmay, glad you like the lib.

Unfortunately this is a limitation of `react-sizeme`. We can only track a single dom element per instance. I am guessing it _may_ be possible to perform some magic under the hood to bind a track against multiple root dom nodes on a react fragment based component, however, I think this would introduce some complexity and possible issues. I'd prefer if we kept this as a known limitation.

The "fix" in your case would be to track a wrapping element.
