### ISSUE TITLE
height doesnt get measured in some cases

### ISSUE THREAD

**Issue by ghost** [ctrlplusb/react-sizeme#175]
https://codesandbox.io/s/frosty-mcnulty-ymdlt
I'm trying to make a separate desktopView and tabbedView, and to pass width and height from sizeme down to these components as props. For some reason it works on desktopView but on tabbedView only width is measured, this can be seen from console output.
I'm new to web development, so all kinds of advice is welcome.

**Comment by ctrlplusb** [comment]
I believe it is measuring the height of your `TabbedView` component. You need to surround the elements in your `TabbedView` component with a wrapping html element. The size me tracking only works on a single child element. This may make a difference.

**Comment by kaarel2X** [comment]
If i change <></> to <div></div> in tabbedView the height starts counting up.
Should i use some other html tag?

**Comment by kaarel2X** [comment]
If i change `<></>` to `<div></div>`  the height starts counting up.
Should i use some other html tag?

**Comment by ctrlplusb** [comment]
Yeah, you have to have a root dom element. This is a known restriction with React Sizeme. It needs the root element to be a singular dom element that it can use to monitor.
