### ISSUE TITLE
Position absolute on container div

### ISSUE THREAD

**Issue by arbesfeld** [ctrlplusb/react-sizeme#20]
Hi! It seems like wrapping a div in `sizeMeHOC` causes the outermost div to have a `style: position='relative` attribute to be attached. This conflicts in cases where we set the position via a class on the outermost div.

Here is a "pseudo" reproduction:

```
class Foo extends Component {
   render() {
     return <div className="absolute" />
   }
}

export default sizeMeHOC()(Foo);
```

**Comment by ctrlplusb** [comment]
Hi @arbesfeld!

Thanks for the report.  I'll look into this case.
