### ISSUE TITLE
React 17 support

### ISSUE THREAD

**Issue by mtmacdonald** [ctrlplusb/react-sizeme#202]
Hi, please can we have support for React 17 so I don't get this peer dependency warning upon npm install in my React 17 projects. Thanks!

npm WARN react-sizeme@2.6.12 requires a peer of react-dom@^0.14.0 || ^15.0.0-0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.

**Comment by Himadu2000** [comment]
#201 , #204

**Comment by ctrlplusb** [comment]
Coming soon. :)

**Comment by ctrlplusb** [comment]
Tis done. 🙏
