### ISSUE TITLE
HOC onSize callback alternative usage example not working

### ISSUE THREAD

**Issue by modemmute** [ctrlplusb/react-sizeme#203]
The example presented in the "HOC Usage" / "'onSize' callback alternative usage" is not working.

https://codesandbox.io/s/react-sizeme-test-8wooy

The returned object only contains a value for the width. The height and position are null. Or am I doing something wrong? I tried downgrading the React & React-DOM version back down to 16.8 with the same results. Any help appreciated!

**Comment by ctrlplusb** [comment]
You need to add `monitorHeight` to the configuration options. 

```javascript
sizeMe({ monitorHeight: true })(Component);
```

The position is never tracked. Sorry that is an artifact from a failed experiment.
