### ISSUE TITLE
PropType Validation fails 

### ISSUE THREAD

**Issue by larrydahooster** [ctrlplusb/react-sizeme#3]
Hey, I tested your library and it works pretty good so far. Anyhow I get the following error on initialization: 

> sizeme-example.js:691 Warning: Failed propType: Required prop `size.width` was not specified in `SizeMeRender`. Check the render method of `SizeAwareComponent`

I checked the code and you set 
```javascript
SizeMeRender.propTypes = {
  ...
    size: PropTypes.shape({
      width: PropTypes.number.isRequired,
      height: PropTypes.number.isRequired,
    })
  };
```

but width and height are undefined in the first runs (which is pretty much the intended functionality). 

![bildschirmfoto 2016-04-15 um 11 20 17](https://cloud.githubusercontent.com/assets/4989851/14557196/5b4721fa-02fc-11e6-8a66-a29885043e3c.png)

Wouldn't it be better to change it to:
```javascript
SizeMeRender.propTypes = {
  ...
    size: PropTypes.shape({
      width: PropTypes.number,
      height: PropTypes.number,
    }).isRequired
  };
``` 

This way you enforce the shape, but allow the props inside of the shape to be undefined?

**Comment by ctrlplusb** [comment]
Well spotted sir thank you. Hmmm, I need to get my test environment to throw on warnings. I'll look into that. Expect a patch today. 

Much appreciate the time you took to test this for me.

**Comment by ctrlplusb** [comment]
Sorted thank you! 💖
