### ISSUE TITLE
Cannot read property 'insertBefore' of null

### ISSUE THREAD

**Issue by emiloberg** [ctrlplusb/react-sizeme#6]
As I work in an enterprise portal environment I have to deliver my React bundles in a quite unorthodox way. 

I attach the Webpack build bundle to the window object. The `output` property of my Webpack config looks a little bit like this:
```
{
	libraryTarget: 'var',
	library: ['reactComponents', 'myStuff123']
}
```

I then pick up the component from the window object (e.g. `window.reactComponents.myStuff123`) and render the React component as such:

```
        ReactDOM.render(
                React.createElement(window.reactComponents.myStuff123),
                document.getElementById('UNIQUE_ID')
        );
```

However, as I add a package, which includes react-resizeme, to the window object I guess that it's immediately trying to set up some event listeners or such, because I get this error:
> Uncaught TypeError: Cannot read property 'insertBefore' of null

Is there any way of postponing the execution until it's actually rendered?

#### Loading example
A full example of the HTML and loading mechanisms looks like this:

```
<!DOCTYPE html>
<html>
<head>
    <script src="react-0.14.8.min.js"></script>
    <script src="react-dom-0.14.8.min.js"></script>
    <script src="bundle.js"></script>
</head>
<body>

<div id="UNIQUE_ID"></div>

<script>
    (function(){
        ReactDOM.render(
                React.createElement(window.reactComponents.NamespacedReactComponent),
                document.getElementById('UNIQUE_ID')
        );
    })();
</script>
</body>
</html>
```

**Comment by ctrlplusb** [comment]
Hmmm, am struggling to think why this is. Could you please link me to the package that is consuming react-sizeme'?

**Comment by ctrlplusb** [comment]
Or a sample project that I could use for debugging... :)

**Comment by ctrlplusb** [comment]
I've just done a patch release which includes a fix for event listener race condition issues with unmounted components.  It may help your case, please try and let me know.

https://github.com/ctrlplusb/react-sizeme/releases/tag/v2.0.1

**Comment by tonyxiao** [comment]
Seeing a similar issue as well.

**Comment by ctrlplusb** [comment]
@tonyxiao any chance you could throw up a sample project for me? I'm more than happy to debug the issue.

**Comment by ctrlplusb** [comment]
@tonyxiao I see you have forked and attempted to lazy load the resizer.  Did it have any effect on the issue?

**Comment by tonyxiao** [comment]
@ctrlplusb yes that fixed the issue for me. I haven't figured out "why" it fixes the issue other than it does :P

**Comment by tonyxiao** [comment]
It crashes even at import time due to importing an external package `element-size-monitor` (or something like that, forgot the exact name)

**Comment by tonyxiao** [comment]
WIll see if I can get a super clean example later.

**Comment by ctrlplusb** [comment]
@tonyxiao great to know.  Thanks for looking into this, I think I understand what is going on now.  Don't worry about a sample project.  I think we can move forward with this fix. Are you happy to send a PR?

**Comment by ctrlplusb** [comment]
There was a patch release available for `element-resize-detector` so I have updated `react-sizeme` and have done a release.

**Comment by tonyxiao** [comment]
Sweet, thank you @ctrlplusb for being so responsive!

**Comment by ctrlplusb** [comment]
No probs. :)  Thanks for your help! :)

Just to be clear my recent change doesn't include your changes.  Are you happy to proceed with a PR?  I don't mind completing it either if you have your hands full.

**Comment by tonyxiao** [comment]
Yep created. https://github.com/ctrlplusb/react-sizeme/pull/8

**Comment by ctrlplusb** [comment]
Thanks @tonyxiao!
