### ISSUE TITLE
Optional clamping for reported width and height

### ISSUE THREAD

**Issue by kachkaev** [ctrlplusb/react-sizeme#74]
Hey Sean,

Thanks a lot for your component – it saved me a couple of hours of life :–)

Not sure you would want to take this on board, but here is a thought that came to me when I was using [Mapbox GL](https://github.com/uber/react-map-gl ) wrapped into `react-sizeme`. There was an issue when my container div shrunk to 0 – WebGL immediately threw a nasty error because the viewport had to be at least 1 px in size. Here is my workaround for this:

```js

// MySuperMap = ...

// Do not allow width / height be 0
const sizeMeFix = (ComponentToWrap) => ({ size, ...rest }) => {
  const {
    width,
    height,
  } = size || {};

  const fixedSize = {
    width: isNumber(width) ? Math.max(width, 1) : width,
    height: isNumber(height) ? Math.max(height, 1) : height,
  };

  return <ComponentToWrap {...rest} size={fixedSize} />;
};

const MySizedSuperMap = sizeMe({
    monitorHeight: true,
    refreshRate: 200,
})(sizeMeFix(MySuperMap));

export default connect(mapStateToProps, mapDispatchToProps)(MySizedSuperMap);
```

So `sizeMe` is a wrapper for another wrapper called `sizeMeFix`, which makes sure that the wrapped component does not get incorrect numbers. I know I can fix the size right in the `render()` method of my component, but the size might be requested in a few other methods and this will create unwanted repetitions.

There might be other cases when reported width and height need to be clamped, so maybe having extra options like `reportedMinWidth`, `reportedMaxWidth`, `reportedMinHeight`, `reportedMaxHeight` can be a useful addition to your wrapper:

```js
const MySizedSuperMap = sizeMe({
   monitorHeight: true,
   refreshRate: 200, 
   reportedMinHeight: 1,
   reportedMinWidth: 1,
})(MySuperMap);
```

What do you think?

**Comment by ctrlplusb** [comment]
Hi! Thanks for this.

I've just gotten back from an intense holiday :)

I'll review this when I have gathered the pieces. :)

**Comment by ctrlplusb** [comment]
Hi @kachkaev 

Let me see if I am understanding this correctly.

- You have a _Mapbox GL_ component which is wrapped by a _SizeMe_ component. 
- During the rendering cycles of the _Mapbox GL_ component there is a case where the container is 0 in height/width, which then get provided to the _Mapbox GL_ component.
- You are then using these provided width/height values within the _Mapbox GL_  component which then causes it to fall over as it requires a minimum height/width of 1.

Is my understanding correct?

**Comment by kachkaev** [comment]
Yep, exactly. I pass width and height from `sizeMe` as props to `<Map />`. If these numbers are zero, the map component crashes. This is why I introduce another higher-order component `sizeMeFix`, which sits between `sizeMe` and the map container (`MySuperMap`) and guards the map from receiving zeros.

My suggestion is about adding optional boundaries to the reported width and height in `sizeMe`. I understand that this would make the component stop telling truth in certain cases, but this is what might needed in a situation like mine.

**Comment by ctrlplusb** [comment]
Okay sweet.

Hmmm, I definitely don't want to consider adding this "clamping feature" to this library as I feel it's very use case specific.  What I would instead recommend is that you create your own HOC, for example `ClampedSizeMe`, that simply wraps the default `SizeMe` HOC and ensures that your requirements are implemented.  Then you can simply import and use the `ClampedSizeMe` HOC instead of mine. :)

**Comment by kachkaev** [comment]
OK, makes sense. `sizeMeFix` in my example was an attempt to implement that `ClampedSizeMe` component, just thought that integrating the feature into the original one can make the code cleaner. Hope that your discussion here helps others!

**Comment by ctrlplusb** [comment]
For example...

`ClampedSizeMe.js`

```typescript
import sizeMe from 'react-sizeme';

function SizeClampComponent(WrappedComponent) {
  return function ClampedSizeComponent({ size, ...otherProps }) {
    const {
      width,
      height,
    } = size || {};

    const fixedSize = {
      width: isNumber(width) ? Math.max(width, 1) : width,
      height: isNumber(height) ? Math.max(height, 1) : height,
    };

    return <WrappedComponent {...rest} size={fixedSize} />;
  }
}

function ClampedSizeMe(config) {
  return function WrapComponent(WrappedComponent) {
    return sizeMe(config)(SizeClampComponent(WrappedComponent));
  };
}

export default ClampedSizeMe;
```

Then use it like so:
```typescript
import clampedSizeMe from './hocs/ClampedSizeMe';

const MySizedSuperMap = clampedSizeMe({
    monitorHeight: true,
    refreshRate: 200,
})(MySuperMap)
```

**Comment by ctrlplusb** [comment]
@kachkaev see the example above :)

Thanks for bringing this up!  I am sure it will definitely help someone else with a similar issue. :)
