### ISSUE TITLE
add "mapDimensionsToProps" option

### ISSUE THREAD

**Issue by slorber** [ctrlplusb/react-sizeme#82]
Hi,

Current implementation seems great. However often our wrapped component will often use width / height to define "breakpoints" from which the component should render differently according to its size.

A problem with current implementation is that it injects width/height directly to wrapped component, so each time the dimensions changes, the wrapped component will generally re-render because of a props change. If the wrapped component is expensive to render it can be a problem.

It would really help if we had a "mapDimensionsToProps" option for the HOC.

The default would be retrocompatible with current behavior:

```javascript
const sizeMeConfig = {
  monitorWidth: true,  
  monitorHeight: false, 
  refreshRate: 16,
  mapDimensionsToProps: dimensions => dimensions
};
```

but it would be possible to customize props passed to our wrapped component. For example imagine I want my wrapped component to customize itself when it is a perfect square, I don't need it to re-render on every dimensions changes. Just injecting it a boolean "isSquare" should be enough and would allow to prevent unnecessary renderings easily with shouldComponentUpdate.

```javascript
const sizeMeConfig = {
  monitorWidth: true,  
  monitorHeight: false, 
  refreshRate: 16,
  mapDimensionsToProps: ({width,height}) => {isSquare: (width === height)}
};
```

I'm using this on my code and it works great
https://gist.github.com/slorber/27006e27997464c9f737ac22a8a89a94

**Comment by slorber** [comment]
Erf just found out about your solution to this problem: https://github.com/ctrlplusb/react-component-queries

**Comment by ctrlplusb** [comment]
I probably should add this to the readme though...

**Comment by ctrlplusb** [comment]
I've updated the [docs](https://github.com/ctrlplusb/react-sizeme#react-component-queries-a-useful-abstraction)

Thanks! 💖

**Comment by slorber** [comment]
great :)
