### ISSUE TITLE
Support for debounce

### ISSUE THREAD

**Issue by peterjwest** [ctrlplusb/react-sizeme#97]
Can you add support for debounce as an alternative to throttling? This can be useful for a smoother resize experience and reduced recalculation thrashing.

**Comment by ctrlplusb** [comment]
It's definitely something I could consider.  Toggling the refresh mode between debounce and throttle.

**Comment by ctrlplusb** [comment]
@peterjwest this is coming soon. :)

**Comment by ctrlplusb** [comment]
@peterjwest good to go! :) v2.2.0

**Comment by peterjwest** [comment]
Amazing! thanks.
