### ISSUE TITLE
`refreshMode: 'debounce'` delays first render significantly.

### ISSUE THREAD

**Issue by nomcopter** [ctrlplusb/react-sizeme#99]
It should not wait to read the size from the DOM for the first render.

**Comment by ctrlplusb** [comment]
You can disable the placeholder render feature by setting the global flag:

```javascript
import sizeMe from 'react-sizeme';
sizeMe.enableSSRBehaviour = false;
```

That's a good caveat you caught in regards to switching out to debounce.  I'll have to amend the docs.

**Comment by ctrlplusb** [comment]
I am also going to consider creating an alias to the above property. Something like `enablePlaceholderRender`...

Will give it some thought.

**Comment by nomcopter** [comment]
Hmm, could work. Is that better than explicitly checking the size and bypassing `refreshDelayStrategy` on the first render?

**Comment by ctrlplusb** [comment]
I am going to give this one some thought and some time to simmer.  I have a use case in my own project for the use of debounce so I'll get a first hand sense of the issues around the current implementation.  I may need to consider some further configuration options, but definitely want to try and keep things as simple as possible.

**Comment by nomcopter** [comment]
The workaround is working well for me, thanks for the quick response!
